import { PropsWithChildren } from 'react'

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import AppProvider from './AppProvider'
import './globals.scss'

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900']
})

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export const revalidate = 3600

export default function RootLayout({ children }: PropsWithChildren<unknown>) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<div className='p-2'>
					<AppProvider>
						Root Layout
						{children}
					</AppProvider>
				</div>
			</body>
		</html>
	)
}
