export const ACCESS_JWT_SECRET = 'ACCESS_JWT_SECRET';
export const REFRESH_JWT_SECRET = 'REFRESH_JWT_SECRET';
export const REFRESH_COOKIE = 'refresh_token';
export const ACCESS_JWT_STRATEGY = 'ACCESS_JWT_STRATEGY';
export const REFRESH_JWT_STRATEGY = 'REFRESH_JWT_STRATEGY';
